In [2]:
import numpy as np  # NUMPY
import random

In [5]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.int16)
print(a)
print(a[0])
a.dtype

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


dtype('int16')

In [8]:
np.arange(10,100,5).reshape(3,6)

array([[10, 15, 20, 25, 30, 35],
       [40, 45, 50, 55, 60, 65],
       [70, 75, 80, 85, 90, 95]])

In [9]:
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [10]:
np.arange(10000).reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [24]:
a = np.array([[1,2,3],[4,5543,6],[7,842,9]], dtype=np.int16)
b = np.array([[1,656,3654],[4,5654,6],[75,85,69]], dtype=np.int16)
a + b

array([[    2,   658,  3657],
       [    8, 11197,    12],
       [   82,   927,    78]], dtype=int16)

In [25]:
rnd = np.random.default_rng(1)
a = rnd.random((4,4))
print(a)

[[0.51182162 0.9504637  0.14415961 0.94864945]
 [0.31183145 0.42332645 0.82770259 0.40919914]
 [0.54959369 0.02755911 0.75351311 0.53814331]
 [0.32973172 0.7884287  0.30319483 0.45349789]]


In [26]:
a += 2
print(a)

[[2.51182162 2.9504637  2.14415961 2.94864945]
 [2.31183145 2.42332645 2.82770259 2.40919914]
 [2.54959369 2.02755911 2.75351311 2.53814331]
 [2.32973172 2.7884287  2.30319483 2.45349789]]


In [18]:
b = np.arange(16).reshape(4,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [23]:
a += b
print(a)
a.max()

[[ 2.51182162  7.9504637  12.14415961 17.94864945]
 [22.31183145 27.42332645 32.82770259 37.40919914]
 [42.54959369 47.02755911 52.75351311 57.53814331]
 [62.32973172 67.7884287  72.30319483 77.45349789]]


77.45349788948064

In [32]:
c = np.linspace(0,1,6).reshape(2,3)
print(c)
c[0].sum(axis=0)
c[1].sum(axis=0)

[[0.  0.2 0.4]
 [0.6 0.8 1. ]]


2.4000000000000004

In [37]:
d = np.ones(12)
print(d)
print(d.sum())
len(d)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
12.0


12

In [40]:
a = np.arange(20)*2
print(a)
print(a[3])
print(a[3:])


[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
6
[ 6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [41]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [42]:
a[0:4,0]

array([1., 1., 1.])

In [ ]:
# PRESTAVKA DO 19:50

In [44]:
b = rnd.random((5,5))
print(b)
for riadok in b:
    print(riadok)

[[0.85263284 0.59294102 0.26009745 0.83988152 0.50949588]
 [0.51088888 0.75303021 0.14792204 0.81962672 0.68328691]
 [0.78709694 0.19161626 0.80236416 0.19132393 0.08155262]
 [0.85522697 0.8612835  0.8765371  0.47190972 0.27404839]
 [0.00709183 0.6457209  0.71990938 0.83556922 0.28187783]]
[0.85263284 0.59294102 0.26009745 0.83988152 0.50949588]
[0.51088888 0.75303021 0.14792204 0.81962672 0.68328691]
[0.78709694 0.19161626 0.80236416 0.19132393 0.08155262]
[0.85522697 0.8612835  0.8765371  0.47190972 0.27404839]
[0.00709183 0.6457209  0.71990938 0.83556922 0.28187783]


In [47]:
for riadok in b.flat:
    print(riadok)

0.8526328384806567
0.592941018104284
0.2600974477372232
0.8398815210314088
0.5094958815215094
0.510888884466533
0.7530302077021779
0.14792203578495655
0.819626719119277
0.6832869060032571
0.787096941554801
0.19161625902013524
0.80236416113453
0.19132392605720028
0.08155261736351271
0.8552269742870702
0.8612834961776684
0.8765370964165805
0.4719097193587902
0.2740483886137183
0.007091828603166261
0.6457208955749478
0.719909383508693
0.8355692165002742
0.28187782736454214


In [48]:
b.resize(2,10)
print(b)

[[0.85263284 0.59294102 0.26009745 0.83988152 0.50949588 0.51088888
  0.75303021 0.14792204 0.81962672 0.68328691]
 [0.78709694 0.19161626 0.80236416 0.19132393 0.08155262 0.85522697
  0.8612835  0.8765371  0.47190972 0.27404839]]


In [49]:
b.reshape(5,4)

array([[0.85263284, 0.59294102, 0.26009745, 0.83988152],
       [0.50949588, 0.51088888, 0.75303021, 0.14792204],
       [0.81962672, 0.68328691, 0.78709694, 0.19161626],
       [0.80236416, 0.19132393, 0.08155262, 0.85522697],
       [0.8612835 , 0.8765371 , 0.47190972, 0.27404839]])

In [50]:
np.split(b,2)

[array([[0.85263284, 0.59294102, 0.26009745, 0.83988152, 0.50949588,
         0.51088888, 0.75303021, 0.14792204, 0.81962672, 0.68328691]]),
 array([[0.78709694, 0.19161626, 0.80236416, 0.19132393, 0.08155262,
         0.85522697, 0.8612835 , 0.8765371 , 0.47190972, 0.27404839]])]

In [51]:
np.fromfunction(lambda x,j: x+j, (3,3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [54]:
b = rnd.random((5))
print(b)
sorted_b = np.sort(b)
print(sorted_b)
sorted_b[::-1]

[0.67345989 0.91908862 0.82682533 0.88552027 0.66035538]
[0.66035538 0.67345989 0.82682533 0.88552027 0.91908862]


array([0.91908862, 0.88552027, 0.82682533, 0.67345989, 0.66035538])